name: "Join Multiple Jobs"
description: "This action will fail if any of the monitored jobs fail."

inputs:
  job_names:
    type: string
  github_token:
    description: The Github token to authenticate PR operations.
    required: true

runs:
  using: composite
  steps:
    - name: Check Previous Jobs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        JOB_NAMES: ${{ inputs.job_names }}
        CURRENT_JOB_ID: ${{ github.job }}
      run: |
        repo_dir="${PWD}"
        cd '${{ github.action_path }}'
        bazel_cmd=( bazelisk run //tools:check_jobs -- )
        [[ -n "${JOB_NAMES:-}" ]] && bazel_cmd+=( --job_names "${JOB_NAMES}" )
        "${bazel_cmd[@]}"
